sudo: true
language: node_js
node_js:
  - '10'

branches:
  only:
    - /.*/

# Keep the npm cache around to speed up installs
cache:
  npm: true
  directories:
    - '$HOME/.npm'

before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc

install:
  - pip install --user awscli
  - yarn install --production=false

before_script:
  - yarn install

script:
  - yarn lint
  - yarn doc
  - yarn build
  - 'if [[ $TRAVIS_PULL_REQUEST != "false" ]]; then bash scripts/publish.sh; fi'
  - yarn test

deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/publish.sh
    on:
      branch: develop
  - provider: script
    skip_cleanup: true
    script: bash scripts/publish.sh
    on:
      branch: master

notifications:
  email:
    on_failure: always
